In [1]:
import pandas as pd
import numpy as np

In [3]:
df_knn = pd.read_csv('df_final_knn.csv')

In [5]:
df_knn

,Unnamed: 0,averageRating,numVotes,originalTitle,genres,title,decade,action,adventure,animation,...,1930,1940,1950,1960,1970,1980,1990,2000,2010,2020
0,0,8.1,59477.0,All Quiet on the Western Front,war,À l'Ouest rien de nouveau,1930,0,0,0,...,1,0,0,0,0,0,0,0,0,0
1,1,7.5,14217.0,Animal Crackers,musical,"Animal crackers, l'explorateur en folie",1930,0,0,0,...,1,0,0,0,0,0,0,0,0,0
2,2,7.7,14548.0,Der blaue Engel,music,L'ange bleu,1930,0,0,0,...,1,0,0,0,0,0,0,0,0,0
3,3,7.2,12871.0,Little Caesar,drama,Le petit César,1930,1,0,0,...,1,0,0,0,0,0,0,0,0,0
4,4,7.3,13463.0,L'âge d'or,drama,L'Âge d'or,1930,0,0,0,...,1,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5873,5873,7.6,29542.0,J'ai perdu mon corps,fantasy,J'ai perdu mon corps,2010,0,0,1,...,0,0,0,0,0,0,0,0,1,0
5874,5874,6.4,7564.0,Isi & Ossi,romance,Isi & Ossi,2020,0,0,0,...,0,0,0,0,0,0,0,0,0,1
5875,5875,8.0,11343.0,Metri Shesh Va Nim,drama,La loi de Téhéran,2010,1,0,0,...,0,0,0,0,0,0,0,0,1,0
5876,5876,6.8,5305.0,Sylvie's Love,romance,Pour l'amour de Sylvie,2020,0,0,0,...,0,0,0,0,0,0,0,0,0,1
5877,5877,8.5,17687.0,Kaithi,thriller,Kaithi,2010,1,0,0,...,0,0,0,0,0,0,0,0,1,0

In [130]:
df_knn[df_knn['title'].str.contains('Interstellar')].shape[0] > 1

False

In [6]:
from sklearn.neighbors import KNeighborsClassifier, NearestNeighbors

In [8]:
X = df_knn[['averageRating', 'numVotes', 'action', 'adventure', 'animation', 'biography', 'comedy',
       'crime', 'documentary', 'drama', 'family', 'fantasy', 'film-noir',
       'history', 'horror', 'music', 'musical', 'mystery', 'news', 'romance',
       'sci-fi', 'sport', 'thriller', 'war', 'western', '1930', '1940', '1950',
       '1960', '1970', '1980', '1990', '2000', '2010', '2020']]

In [10]:
model_film = NearestNeighbors(metric = 'minkowski', n_neighbors=10, ).fit(X)

In [13]:
model_film.kneighbors(df_knn.loc[df_knn['title'].str.contains("Mission C"), ['averageRating', 'numVotes', 'action', 'adventure', 'animation', 'biography', 'comedy',
       'crime', 'documentary', 'drama', 'family', 'fantasy', 'film-noir',
       'history', 'horror', 'music', 'musical', 'mystery', 'news', 'romance',
       'sci-fi', 'sport', 'thriller', 'war', 'western', '1930', '1940', '1950',
       '1960', '1970', '1980', '1990', '2000', '2010', '2020']])

(array([[ 0.        ,  4.00499688, 25.19841265, 31.12876483, 35.09985755,
         42.05960057, 50.06995107, 50.08003594, 58.06901067, 65.05659075]]),
 array([[2619, 1930,  540, 2200, 5591, 5688, 5226, 5710, 3088, 1814]]))

In [15]:
df_knn.iloc[1930]

Unnamed: 0                   1930
averageRating                 6.5
numVotes                    50987
originalTitle     Dangerous Minds
genres                      drama
title            Esprits rebelles
decade                       1990
action                          0
adventure                       0
animation                       0
biography                       1
comedy                          0
crime                           0
documentary                     0
drama                           1
family                          0
fantasy                         0
film-noir                       0
history                         0
horror                          0
music                           0
musical                         0
mystery                         0
news                            0
romance                         0
sci-fi                          0
sport                           0
thriller                        0
war                             0
western                         0
1930                            0
1940                            0
1950                            0
1960                            0
1970                            0
1980                            0
1990                            1
2000                            0
2010                            0
2020                            0
Name: 1930, dtype: object

In [139]:
movie = input('Insere un film')
def recommandation2(movie):
    if df_knn[df_knn['title'].str.contains(movie)].shape[0] > 1:
        print("Plusieurs films contiennent ce nom, choisissez parmis l'un d'eux : ")
        return df_knn[df_knn['title'].str.contains(movie)]
    else:
        index_reco = model_film.kneighbors(df_knn.loc[df_knn['title'].str.contains(movie), ['averageRating', 'numVotes', 'action', 'adventure', 'animation', 'biography', 'comedy','crime', 'documentary', 'drama', 'family', 'fantasy', 'film-noir','history', 'horror', 'music', 'musical', 'mystery', 'news', 'romance','sci-fi', 'sport', 'thriller', 'war', 'western', '1930', '1940', '1950','1960', '1970', '1980', '1990', '2000', '2010', '2020']])
        recommended_movie = df_knn.iloc[df_knn.index.isin(index_reco[1][0][1:9])]
        return recommended_movie

Insere un film Le Hobbit: Un Voyage Inattendu

In [140]:
recommandation2(movie)

,Unnamed: 0,averageRating,numVotes,originalTitle,genres,title,decade,action,adventure,animation,...,1930,1940,1950,1960,1970,1980,1990,2000,2010,2020
675,675,8.3,787831.0,A Clockwork Orange,sci-fi,Orange mécanique,1970,0,0,0,...,0,0,0,0,1,0,0,0,0,0
1130,1130,8.3,780972.0,Scarface,drama,Scarface,1980,0,0,0,...,0,0,0,0,0,1,0,0,0,0
2633,2633,8.5,773388.0,The Pianist,music,Le pianiste,2000,0,0,0,...,0,0,0,0,0,0,0,1,0,0
3295,3295,8.2,788205.0,Toy Story 3,comedy,Toy Story 3,2010,0,1,1,...,0,0,0,0,0,0,0,0,1,0
3386,3386,6.9,785007.0,Captain America: The First Avenger,sci-fi,Captain America: First Avenger,2010,1,1,0,...,0,0,0,0,0,0,0,0,1,0
3576,3576,7.0,785971.0,Thor,fantasy,Thor,2010,1,1,0,...,0,0,0,0,0,0,0,0,1,0
4272,4272,7.7,792967.0,Gravity,sci-fi,Gravity,2010,0,1,0,...,0,0,0,0,0,0,0,0,1,0
4573,4573,7.7,780031.0,Captain America: The Winter Soldier,sci-fi,Captain America: Le soldat de l'hiver,2010,1,1,0,...,0,0,0,0,0,0,0,0,1,0

In [131]:
def recommandation(x):
    if df_knn[df_knn['title'].str.contains(x)].shape[0] > 1:
        print("Plusieurs films contiennent ce nom, choisissez parmis l'un d'eux : ")
        return df_knn[df_knn['title'].str.contains(x)]
    else:
        index_reco = model_film.kneighbors(df_knn.loc[df_knn['title'].str.contains(x), ['averageRating', 'numVotes', 'action', 'adventure', 'animation', 'biography', 'comedy','crime', 'documentary', 'drama', 'family', 'fantasy', 'film-noir','history', 'horror', 'music', 'musical', 'mystery', 'news', 'romance','sci-fi', 'sport', 'thriller', 'war', 'western', '1930', '1940', '1950','1960', '1970', '1980', '1990', '2000', '2010', '2020']])
        recommended_movie = df_knn.iloc[df_knn.index.isin(index_reco[1][0][1:9])]
        return recommended_movie

In [132]:
recommandation("Harry Potter")

Plusieurs films contiennent ce nom, choisissez parmis l'un d'eux :

,Unnamed: 0,averageRating,numVotes,originalTitle,genres,title,decade,action,adventure,animation,...,1930,1940,1950,1960,1970,1980,1990,2000,2010,2020
2583,2583,7.6,702180.0,Harry Potter and the Sorcerer's Stone,fantasy,Harry Potter à l'école des sorciers,2000,0,1,0,...,0,0,0,0,0,0,0,1,0,0
2769,2769,7.4,584153.0,Harry Potter and the Chamber of Secrets,fantasy,Harry Potter et la Chambre des secrets,2000,0,1,0,...,0,0,0,0,0,0,0,1,0,0
2790,2790,7.9,582221.0,Harry Potter and the Prisoner of Azkaban,fantasy,Harry Potter et le Prisonnier d'Azkaban,2000,0,1,0,...,0,0,0,0,0,0,0,1,0,0
2874,2874,7.7,576047.0,Harry Potter and the Goblet of Fire,fantasy,Harry Potter et la Coupe de feu,2000,0,1,0,...,0,0,0,0,0,0,0,1,0,0
3030,3030,7.5,536874.0,Harry Potter and the Order of the Phoenix,family,Harry Potter et l'Ordre du Phénix,2000,1,1,0,...,0,0,0,0,0,0,0,1,0,0
3211,3211,7.6,501253.0,Harry Potter and the Half-Blood Prince,family,Harry Potter et le Prince de sang-mêlé,2000,1,1,0,...,0,0,0,0,0,0,0,1,0,0
3699,3699,7.7,504600.0,Harry Potter and the Deathly Hallows: Part 1,mystery,Harry Potter et les Reliques de la Mort 1ère p...,2010,0,1,0,...,0,0,0,0,0,0,0,0,1,0
4025,4025,8.1,805392.0,Harry Potter and the Deathly Hallows: Part 2,mystery,Harry Potter et les Reliques de la Mort 2ème p...,2010,0,1,0,...,0,0,0,0,0,0,0,0,1,0

In [42]:
index_reco = model_film.kneighbors(df_knn.loc[df_knn['title'].str.contains('Interstellar'), ['averageRating', 'numVotes', 'action', 'adventure', 'animation', 'biography', 'comedy','crime', 'documentary', 'drama', 'family', 'fantasy', 'film-noir','history', 'horror', 'music', 'musical', 'mystery', 'news', 'romance','sci-fi', 'sport', 'thriller', 'war', 'western', '1930', '1940', '1950','1960', '1970', '1980', '1990', '2000', '2010', '2020']])

In [87]:
index_reco[1][0]

array([3600, 4184, 2429,  717, 2428, 1986, 2233, 2320, 4576, 2446])

In [67]:
df_knn.iloc[df_knn.index.isin([index_reco[1][0][1]])]

,Unnamed: 0,averageRating,numVotes,originalTitle,genres,title,decade,action,adventure,animation,...,1930,1940,1950,1960,1970,1980,1990,2000,2010,2020
4184,4184,8.4,1582868.0,The Dark Knight Rises,action,The Dark Knight Rises,2010,1,0,0,...,0,0,0,0,0,0,0,0,1,0